name: check

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Check workspace
        run: cargo check --locked --workspace --all-targets
      - name: Test workspace
        run: cargo test --locked --workspace --all-targets
